package Gajikaryawann;
import java.awt.Dimension;
import java.awt.Toolkit;
public class GajiKaryawan extends javax.swing.JFrame {
    
    int x=0;
    
    public GajiKaryawan() {
        initComponents() ;
        
         Dimension screenSize = 
         Toolkit.getDefaultToolkit().getScreenSize();
            Dimension frameSize = this.getSize();
            if (frameSize.height > screenSize.height) {
                frameSize.height = screenSize.height;
            }
            if (frameSize.width > screenSize.width) {
                frameSize.width = screenSize.width;
            }
            this.setLocation(
                    (screenSize.width - frameSize.width) / 2, 
                    (screenSize.height - frameSize.height) / 2); 

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeljudul = new javax.swing.JLabel();
        labelnama = new javax.swing.JLabel();
        textnama = new javax.swing.JTextField();
        labelgolongan = new javax.swing.JLabel();
        golongan1RadioButton = new javax.swing.JRadioButton();
        golongan2RadioButton = new javax.swing.JRadioButton();
        golongan3RadioButton = new javax.swing.JRadioButton();
        labellama = new javax.swing.JLabel();
        textlama = new javax.swing.JTextField();
        hiitungbutton = new javax.swing.JButton();
        kembalibutton = new javax.swing.JButton();
        labelnik = new javax.swing.JLabel();
        textnik = new javax.swing.JTextField();
        labeltanggal = new javax.swing.JLabel();
        Tanggal = new javax.swing.JComboBox<>();
        Bulan = new javax.swing.JComboBox<>();
        Tahun = new javax.swing.JComboBox<>();
        labelTunjangan = new javax.swing.JLabel();
        textunjangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbdata = new javax.swing.JTable();
        hapusbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        labeljudul.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        labeljudul.setText("Penghitung Gaji Karyawan PT KAI ");

        labelnama.setText("Nama");

        textnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnamaActionPerformed(evt);
            }
        });

        labelgolongan.setText("Golongan");

        golongan1RadioButton.setText("Golongan 1");

        golongan2RadioButton.setText("Golongan 2");

        golongan3RadioButton.setText("Golongan 3");

        labellama.setText("Lama Kerja(Bulan)");

        textlama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlamaActionPerformed(evt);
            }
        });

        hiitungbutton.setText("Hitung");
        hiitungbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiitungbuttonActionPerformed(evt);
            }
        });

        kembalibutton.setText("Kembali");
        kembalibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalibuttonActionPerformed(evt);
            }
        });

        labelnik.setText("NIK");

        labeltanggal.setText("Tanggal Lahir");

        Tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        Tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalActionPerformed(evt);
            }
        });

        Bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        Tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        Tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TahunActionPerformed(evt);
            }
        });

        labelTunjangan.setText("Bonus");

        textunjangan.setEditable(false);

        Tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIK", "Tanggal Lahir", "Lama Kerja", "Gaji"
            }
        ));
        jScrollPane1.setViewportView(Tbdata);

        hapusbutton.setText("Hapus");
        hapusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(labeljudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(hiitungbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(kembalibutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelnik)
                            .addComponent(labelgolongan)
                            .addComponent(labelnama))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textnama, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labeltanggal)
                                .addGap(89, 89, 89)
                                .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textnik, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(golongan1RadioButton)
                                    .addComponent(golongan2RadioButton)
                                    .addComponent(golongan3RadioButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labellama)
                                    .addComponent(labelTunjangan))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textlama, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(hapusbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labeljudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelnama)
                    .addComponent(textnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labeltanggal))
                    .addComponent(Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelnik)
                        .addGap(12, 12, 12)
                        .addComponent(labelgolongan))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(golongan1RadioButton)
                        .addGap(0, 0, 0)
                        .addComponent(golongan2RadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labellama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelTunjangan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textlama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(textunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(golongan3RadioButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiitungbutton)
                    .addComponent(kembalibutton))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hapusbutton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnamaActionPerformed

    private void TanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalActionPerformed

    private void TahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TahunActionPerformed

    private void hiitungbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiitungbuttonActionPerformed
    String nama = textnama.getText();
                int golongan = 0;
                if (golongan1RadioButton.isSelected()) {
                    golongan = 1;
                } else if (golongan2RadioButton.isSelected()) {
                    golongan = 2;
                } else if (golongan3RadioButton.isSelected()) {
                    golongan = 3;
                }
                int lamaKerja = Integer.parseInt(textlama.getText());

                double gajiPokok = hitungGajiPokok(golongan);
                double tunjangan = hitungTunjangan(golongan, lamaKerja);
                double totalGaji = gajiPokok + tunjangan;
                String bonus = tunjangan + "\n";
                textunjangan.setText(bonus);
                Tbdata.setValueAt(textnama.getText(), x, 0);
                Tbdata.setValueAt(textnik.getText(), x, 1);
                String tanggal = Tanggal.getSelectedItem().toString();
                String bulan = Bulan.getSelectedItem().toString();
                String tahun = Tahun.getSelectedItem().toString();
                String tanggalLahir = tanggal + " " + bulan + " " + tahun;
                Tbdata.setValueAt(tanggalLahir, x, 2);
                Tbdata.setValueAt(textlama.getText(), x, 3);
                Tbdata.setValueAt(totalGaji, x, 4);
                x=x+1;

    
    }//GEN-LAST:event_hiitungbuttonActionPerformed

    private void kembalibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalibuttonActionPerformed
        textnama.setText("");
        golongan1RadioButton.setSelected(false);
        golongan2RadioButton.setSelected(false);
        golongan3RadioButton.setSelected(false);
        textlama.setText("");
        textunjangan.setText("");
        textnik.setText("");
        Tanggal.setSelectedIndex(0);
        Bulan.setSelectedIndex(0);
        Tahun.setSelectedIndex(0);
                
   
    }//GEN-LAST:event_kembalibuttonActionPerformed

    private void textlamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlamaActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_textlamaActionPerformed

    private void hapusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbuttonActionPerformed
            Tbdata.setValueAt("", Tbdata.getSelectedRow(), 0);
            Tbdata.setValueAt("", Tbdata.getSelectedRow(), 1);
            Tbdata.setValueAt("", Tbdata.getSelectedRow(), 2);
            Tbdata.setValueAt("", Tbdata.getSelectedRow(), 3);
            Tbdata.setValueAt("", Tbdata.getSelectedRow(), 4);
        
    }//GEN-LAST:event_hapusbuttonActionPerformed
private double hitungGajiPokok(int golongan) {
        double gajiPokok = 0;
        switch (golongan) {
            case 1:
                gajiPokok = 5000000;
                break;
            case 2:
                gajiPokok = 7000000;
                break;
            case 3:
                gajiPokok = 9000000;
                break;
        }
        return gajiPokok;
    }
private double hitungTunjangan(int golongan, int lamaKerja) {
        double tunjangan = 0;
        if (lamaKerja >= 12) {
            switch (golongan) {
                case 1:
                    tunjangan = 0.15 * hitungGajiPokok(golongan);
                    break;
                case 2:
                    tunjangan = 0.2 * hitungGajiPokok(golongan);
                    break;
                case 3:
                    tunjangan = 0.25 * hitungGajiPokok(golongan);
                    break;
            }
        }
        return tunjangan;
    }
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GajiKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GajiKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bulan;
    private javax.swing.JComboBox<String> Tahun;
    private javax.swing.JComboBox<String> Tanggal;
    private javax.swing.JTable Tbdata;
    private javax.swing.JRadioButton golongan1RadioButton;
    private javax.swing.JRadioButton golongan2RadioButton;
    private javax.swing.JRadioButton golongan3RadioButton;
    private javax.swing.JButton hapusbutton;
    private javax.swing.JButton hiitungbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembalibutton;
    private javax.swing.JLabel labelTunjangan;
    private javax.swing.JLabel labelgolongan;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labellama;
    private javax.swing.JLabel labelnama;
    private javax.swing.JLabel labelnik;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTextField textlama;
    private javax.swing.JTextField textnama;
    private javax.swing.JTextField textnik;
    private javax.swing.JTextField textunjangan;
    // End of variables declaration//GEN-END:variables
}
